### ISSUE TITLE
Input sound hangs

### ISSUE THREAD

**Issue by netmate1234** [drowe67/freedv-gui#107]
Expression 'err' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3355
Expression 'ContinuePoll( self, StreamDirection_In, &pollTimeout, &pollCapture )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3907
Expression 'PaAlsaStream_WaitForFrames( stream, &framesAvail, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4285

(all modes)

**Comment by drowe67** [comment]
This is an issue internal to PortAudio - not in the FreeDV source code.  No one else is reporting any similar issues. If it was a FreeDV bug affecting all modes it would be widely reported. It could possibly be due to your specific sound card hardware/drivers.

Can you:
1. Repeat this problem on a basic laptop configuration using just the internal sound card and the test wave files in rx-only mode?
2. Try different sound card hardware.

**Comment by drowe67** [comment]
Closed as no response from OP
