### ISSUE TITLE
FreeDV 2020 TODO

### ISSUE THREAD

**Issue by drowe67** [drowe67/freedv-gui#11]
1. Check Speex noise suppressor works at 16 kHz
1. Check mic and speaker Filters work
1. Are levels correct?  Speaker out tab shows signals (like wia sample) clipping on decode, which looks high to me (David).

**Comment by DG9BFC** [comment]
make it run on processors without avx ;-)

**Comment by tmiw** [comment]
@drowe67, #142 will probably handle item 2. Item 1 seems to already have been handled when multi-RX was added as we're auto-recreating the global Speex object on TX mode changes. Is item 3 still an issue?

**Comment by drowe67** [comment]
It certainly seems like we are close:
1. Adding some code to support Speex with multi-rx is fine progress.  Have there been any tests to determine if it actually suppresses background/ambient noise on 2020?
1. Done :heavy_check_mark: 
1. Good question. This will need to be tested/evaluated too.  If the clipping is real it should be pretty obvious in the decoded audio.  Might just be a display issue.

**Comment by tmiw** [comment]
For what it's worth, I made a couple of 2020 recordings with https://www.youtube.com/watch?v=nMfPqeZjc2c playing in the background, both with and without Speex. You can definitely tell the difference so I'm fairly sure it's working. 👍 

Also, here's what happens when I get the microphone audio to clip: [2020 audio clipping.wav.zip](https://github.com/drowe67/freedv-gui/files/6846419/2020.audio.clipping.wav.zip). Seems like the audio quality definitely takes a hit when it does.

**Comment by drowe67** [comment]
Thanks @tmiw - good work testing :+1  I think we're done!
