### ISSUE TITLE
S-Meter display  on main screen (feature request)

### ISSUE THREAD

**Issue by cybork42** [drowe67/freedv-gui#177]
Dear experts.
In order to detect "**channel already busy again**" it would be helpful to have an **S-Meter display** as part of the main screen.
Many TRX and their hamlib implementation support this feature (I guess hamlib is already used in freeDV anyway), and some transceivers offer S-Meter readings as part of their CAT interface.

What for this suggestion?
When using freeDV for example during skeds, it's sometimes difficult not to overlay with some other ham as audio decoding takes some time, the waterfall may be too slow, but the the S-Meter already be able to suggest someone else transmitting... Also think about a possible upcoming contest capability... you need to see if you're already to late to press PTT...

73 de Andreas (DM4AB).

**Comment by tmiw** [comment]
Is the purpose to show whether there's another signal in general on the frequency or whether someone else is using FreeDV? Because I would think that the sync indicator already in the UI would indicate the latter.

BTW, please repost at https://github.com/drowe67/freedv-gui/discussions as the issues area is for tracking bugs with FreeDV.

**Comment by cybork42** [comment]
moved to "discussions".
