### ISSUE TITLE
Please label experimental modes on the GUI

### ISSUE THREAD

**Issue by HouzuoGuo** [drowe67/freedv-gui#311]
Good day.

There are now 8 modes available for operators, according to the user manual at least two of them (2020 and 2020B) are experimental as of today, and does not mention whether the remaining 6 modes are stable or experimental and subjected to change.

Please label the experimental status on the GUI captions - thank you.

**Comment by tmiw** [comment]
As FreeDV is in active development, modes are subject to change. However, we'll evaluate ways of improving usability making it clearer what modes are in common use. 

Additionally, the latest software defaults to 700D if you haven't set up FreeDV before, so that's probably a good mode to start operating with in the interim.
