### ISSUE TITLE
Please add support for pipewire. 

### ISSUE THREAD

**Issue by Supermagnum** [drowe67/freedv-gui#365]
PipeWire is a project that aims to greatly improve handling of audio and video under Linux. It provides a low-latency, graph-based processing engine on top of audio and video devices that can be used to support the use cases currently handled by both PulseAudio and JACK. PipeWire was designed with a powerful security model that makes interacting with audio and video devices from containerized applications easy, with support for Flatpak applications being the primary goal. 
It is a system of virtual cables for audio and video. 
It's located at:
https://pipewire.org/

It has GUI'S like qpwgraph and Vellum among others.

**Comment by tmiw** [comment]
FreeDV supports being built using PulseAudio instead of PortAudio. This can be done by executing `./build_linux.sh pulseaudio`. Note that PulseAudio is 100% compatible with pipewire, so no additional code should be required for the latter. Please reopen this issue if that doesn't work and we can investigate further.
