### ISSUE TITLE
Record time field on Windows

### ISSUE THREAD

**Issue by drowe67** [drowe67/freedv-gui#39]
The record time field (e.g. Tools - Start/Stop record from radio) doesn't appear on the Windows build.

**Comment by drowe67** [comment]
@tmiw do you know if this is still an issue?  I recall you did some work with these record/playback dialogs recently.

**Comment by tmiw** [comment]
@drowe67, just tested on one of the 1.5.1 builds (unsure if the absolute latest, but doubt I would have made it worse since) and it looks good now:

<img width="562" alt="Screen Shot 2021-01-06 at 11 58 53 PM" src="https://user-images.githubusercontent.com/449242/103866852-48f2c000-507b-11eb-8239-4525fb084595.png">

**Comment by drowe67** [comment]
That's great - good to see it's fixed :+1:
