### ISSUE TITLE
Filter setting sliders too aggressive (1.18.12 pre)

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#463]
Recently the level adjustments for the filters have become too course and difficult to set.
Reported to me by GW3OAJ on Windows and confirmed by me in Linux.

**Comment by tmiw** [comment]
How granular should the filter adjustments be? On macOS at least, each click of the slider seems to produce around a 0.4 dB  adjustment right now.

**Comment by Tyrbiter** [comment]
One thing I noticed is that the freq adjustments make it difficult to return to the original setting. So, for instance, 100Hz is always 96 or 102. Then 3000Hz is always 2964 or 3124.

One small thing, Miscellaneous is mis-spelt as "Miscallenous" in the USER_MANUAL.md and .html files.

**Comment by tmiw** [comment]
> One thing I noticed is that the freq adjustments make it difficult to return to the original setting. So, for instance, 100Hz is always 96 or 102. Then 3000Hz is always 2964 or 3124.

Based on the current code, it seems that it assumes there are 100 possible positions for the sliders, which may not 100% be correct. I'm thinking for frequency sliders, there should be 10000 maximum positions, while anything involving magnitudes should be set somewhere that ensures 0.1 dB granularity. Does that sound reasonable or do you guys have any suggestions?

> One small thing, Miscellaneous is mis-spelt as "Miscallenous" in the USER_MANUAL.md and .html files.

Yep, fixed in https://github.com/drowe67/freedv-gui/pull/466/files#diff-47b5dd4f4aceb13d5c25c92f0a31db61a9cb09e2a96eb3ce45be1db2dccbe9b2.

**Comment by Tyrbiter** [comment]
I'm not sure about the 10,000 positions, I suppose it's fine as long as there isn't a huge array to hold it.

0.1dB granularity might be a bit too granular, I wonder if 0.5dB would work or perhaps 0.25dB?

Other opinions welcomed :)

**Comment by tmiw** [comment]
Another possibility may be simply that the height of the sliders is too short to be able to properly adjust the settings, no matter what `SLIDER_MAX` is set to. I'm reluctant to try to make the window bigger as there have been reports before of various parts of the FreeDV UI not working well on smaller displays, at least so close to 1.8.12.

Anyway, we can play around more and figure out a solution that'll work. 👍

**Comment by Tyrbiter** [comment]
Perhaps the slider is the wrong thing for some settings, maybe a spin-wheel or similar would be better?

I don't see it as a very high priority item but it would be nice to improve it in the next release after 1.8.12 for those that use these settings (I have generally left them alone except for testing basic function).

**Comment by tmiw** [comment]
So, I actually wonder if this is the same issue mentioned on the digitalvoice list earlier today. Try v1.8.12 and let me know how that goes. 👍

**Comment by barjac** [comment]
On 13/07/2023 12:39, Brian wrote:
>     So, I actually wonder if this is the same issue mentioned on the
>     digitalvoice list earlier today. Try v1.8.12 (currently building
>     now) and let me know how that goes. +1
> 
> I see you found some possible errors in the filter settings code. Makes 
> sense to revisit now that the release is done. Well done @tmiw 
> <https://github.com/tmiw> you have been burning the candle at both ends 
> again ;-)
> 

Yes @tmiw you have done a grand job!


I am wondering whether the 'aggressive' report that I heard and then saw 
myself when I tested was simply down to default settings on a new 
install which I have just seen on the latest.

All gains were at max as was the mid range Q.
Attempting to adjust it with that starting point can give strange 
results that are wildly off the scale!

After spending some time returning levels to a flatish starting point 
makes adjustments easier.
Maybe that is what the 'default' button does, but I did not want to try 
that once I had it set. :)

**Comment by tmiw** [comment]
Yeah, the Default button sets the gain/Q to 0 across the board and the bass/mid/treble frequencies as 100, 1500 and 3000 Hz respectively. Apparently this didn't match up with the config file defaults either as if you wiped the settings, the frequencies were 1 Hz across the board.

Anyway, the bug was basically that everything was getting multiplied by 10 when you closed the Filter dialog. As a result, setting Q to e.g. 1 would cause it to get set to 10 when you reopened the dialog, which definitely isn't ideal.

**Comment by tmiw** [comment]
> I notice that the .freedv file has:
> 
> BassFreqHz=100 TrebleFreqHz=3000 MidFreqHz=1500
> 
> in it twice.
> 
> Is that intentional or does it need to have separate names?

Intentional. There's one set with "MicIn" above it and another with "SpkOut".

**Comment by Tyrbiter** [comment]
> > I notice that the .freedv file has:
> > BassFreqHz=100 TrebleFreqHz=3000 MidFreqHz=1500
> > in it twice.
> > Is that intentional or does it need to have separate names?
> 
> Intentional. There's one set with "MicIn" above it and another with "SpkOut".

Oh yes, I should have grep'd above and below 'Freq'
