### ISSUE TITLE
Encryption Option for International DV Chat

### ISSUE THREAD

**Issue by ITCMD** [drowe67/freedv-gui#591]
Has there been the consideration of allowing some sort of encryption within freeDV?

Obviously this would _not_ be useable for USA amateur radio. However, in some countries no such encryption laws exist, and having an option for any type of wartime use would be extremely valuable. Currently only military agencies have this, and having an open-source option would be fantastic.

I would expect this would be somewhat easy to implement (relatively. I know it's not as simple as adding a few lines of code). Something as simple as an optional config file would be great to add this option.

Has this been considered? Do you think someone could come in and create a fork with this feature? If so, how would you suggest they do so? I'd be interested in hiring someone to do it.

**Comment by tmiw** [comment]
Thanks for the feedback! There was a bit of discussion a while back but I'm not sure if we ever came to a conclusion. We'll have to discuss more as a project team and get back to you on that.

**Comment by tmiw** [comment]
Hi @ITCMD! The Project Leadership Team met yesterday to consider your proposal and unfortunately, we're not moving forward with it at this time. Our policy on feature enhancements is that they should be usable by amateurs worldwide, and since encryption would only be usable by some hams outside the US at best, this would not be allowed by the current policy.

That said, please feel free to submit any other feature suggestions to us! We just ask that you provide the following information if possible:

1. How many people want the feature? Please supply contacts details for at least 3 of them.
2. Is this a feature for FreeDV or Codec 2?
    a. If for FreeDV: How will it help enhance HF Digital Voice for Amateur radio?
    b. If for Codec2: How will it enhance open source speech coding?
3. Is this a feature for UHF or VHF? If so please talk to [M17](https://m17project.org/), rather than FreeDV.
4. Does the feature relate to [deprecated](https://github.com/drowe67/codec2#old-code-and-deprecated-features) code that will be deleted in the near future?
5. Is the feature a port to a [non C99 compatible](https://github.com/drowe67/codec2#ports-to-non-c99-compilers) compiler? We have standardized on C99.
6. Is the feature legal for Amateur Radio worldwide? Export Control regulations in many countries limit speech coding to a minimum of 700 bit/s and forbids encryption.
7. Your feature will take effort to implement. If the FreeDV developers work on your feature they won’t be doing other important work on the project. What help can you give in implementing/documenting/testing/supporting the feature?
8. It takes effort from the FreeDV developers to maintain and support features. What help can you give in maintaining/supporting/documenting the feature in the next 1-5 years?
