### ISSUE TITLE
Add a beam heading column to the (internal) reporter.

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#671]
This was suggested by Mooneer during another bug/PR a few weeks ago.

It would be a good addition to the reporter and would only require a 3 digit wide column next to the Locator column to show the great circle beam heading from the current station.

Adding this enhancement request so as to not forget about it :)

**Comment by tmiw** [comment]
Actually I think @Tyrbiter suggested this. How much space remaining do you have in your window?

**Comment by Tyrbiter** [comment]
I think I commented on this because @barjac wondered why US stations were using the message facility to display their QTH. Beam heading might help make this unnecessary, those living in the lower 48 must sometimes have to think which direction another state is from theirs so showing a bearing would eliminate the mental gymnastics.

For the rest of the world it's even more difficult to map a prefix to a great circle bearing.

**Comment by barjac** [comment]
> Actually I think @Tyrbiter suggested this. How much space remaining do you have in your window?

Yes you could be right, I could not quickly find the reference.

With the recent space saving I think there would be enough room if the label did not take more room than the data. Maybe 'Hdg' or 'Deg' would suffice.

**Comment by tmiw** [comment]
Done: https://github.com/drowe67/freedv-gui/pull/672
