### ISSUE TITLE
freedv depends on libwxgtk3.0-gtk3-0v5 during package install on raspberry pi4

### ISSUE THREAD

**Issue by giddygiddybangbang** [drowe67/freedv-gui#683]
Fresh raspberry pi lite bookworm install on rpi4
Download 1.9.8-dev zip
Build seems to go ok but during dpkg install:
dpkg: dependency problems prevent configuration of freedv:
 freedv depends on libwxgtk3.0-gtk3-0v5 (>= 3.0.4+dfsg-3); however:
  Package libwxgtk3.0-gtk3-0v5 is not installed.

**Comment by tmiw** [comment]
As explained on #684, can you explain how you're getting and/or building the FreeDV package? It looks like the latest on Debian bookworm is https://packages.debian.org/bookworm/freedv, which is version 1.8.11.

**Comment by giddygiddybangbang** [comment]
Hello,
I grab the zip file from github and unzip into a src dir. After adding the extra packages needed for source compiles, I run build_linux pulseaudio.
Then make and cpack followed by dpkg install where the error occurs.
This is on a fresh raspberry pi install of bookworm on a rpi4.

Thanks,
Robert

**Comment by tmiw** [comment]
`cpack` isn't actually supported anymore. It was originally used to produce test builds for people but due to various library dependency issues we stopped doing so. That logic in the `CMakeLists.txt` should probably be removed at some point.

That said, Bookworm does seem to have a [freedv package](https://packages.debian.org/bookworm/freedv) but it's definitely an older release vs. what's available on the Git repo. You can also try to scroll to the bottom of the top-level `CMakeLists.txt` file and change the dependencies below as needed, i.e. these lines:

```
    if(USE_PULSEAUDIO)
    SET(CPACK_DEBIAN_PACKAGE_DEPENDS "codec2 (>= 1.1.1), lpcnet (>= 0.5.0), libspeexdsp1 (>= 1.2~rc1.2-1+b2), libsamplerate0 (>= 0.1.9-2), libwxgtk3.0-gtk3-0v5  (>= 3.0.4+dfsg-3), libpulse0 (>= 14.2-2), libhamlib2 (>= 3.3-10build1), libasound2 (>= 1.1.8-1), libao4 (>= 1.2.2+20180113-1), libgsm1 (>= 1.0.18-2), libsndfile1 (>= 1.0.28-6)")
    else(USE_PULSEAUDIO)
    SET(CPACK_DEBIAN_PACKAGE_DEPENDS "codec2 (>= 1.1.1), lpcnet (>= 0.5.0), libspeexdsp1 (>= 1.2~rc1.2-1+b2), libsamplerate0 (>= 0.1.9-2), libwxgtk3.0-gtk3-0v5  (>= 3.0.4+dfsg-3), libportaudio2 (>= 19.6.0-1build1), libhamlib2 (>= 3.3-10build1), libasound2 (>= 1.1.8-1), libao4 (>= 1.2.2+20180113-1), libgsm1 (>= 1.0.18-2), libsndfile1 (>= 1.0.28-6)")
    endif(USE_PULSEAUDIO)
```
