### ISSUE TITLE
[Question] IF Filter & FreeDV

### ISSUE THREAD

**Issue by Nokia808** [drowe67/freedv-gui#701]
Hello again !

What is ideal & most suitable IF Filter band width ?

**Comment by tmiw** [comment]
~3 KHz is likely fine for most uses, especially since it allows you to easily pick up other users regardless of what mode they're using. We haven't done much official testing with narrower filters. 

However, it's possible that narrower filters may help in certain situations; IIRC the narrowest mode (700D) only needs around 1-1.1 KHz bandwidth.

**Comment by Nokia808** [comment]
@tmiw 

Does IF Filter BW = 3 KHz make something bad for 700D mode ?

**Comment by tmiw** [comment]
> Does IF Filter BW = 3 KHz make something bad for 700D mode ?

It shouldn't as it's much wider than the ~1 KHz of bandwidth that it requires. The wider bandwidth is preferred mainly due to the other modes being wider than 1 KHz (thus reducing the need to continually adjust the filters).

**Comment by Nokia808** [comment]
@tmiw 

Many thanks ! Question answered !

@tmiw & @tyrbiter I welcome sked with you if you like & if you have a time !
